---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: _i18n/en/_posts
  label: English
  create: documents
  match: "*"
  exclude: "*.yml"
  templates:
  - en-post
- type: directory
  path: _i18n/ja/_posts
  label: Japanese
  create: documents
  match: "*"
  exclude: "*.yml"
  templates:
  - ja-post
- type: directory
  path: _i18n/zh-Hans/_posts
  label: Simplified Chinese
  create: documents
  match: "*"
  templates:
  - zh-cn-post
- type: directory
  path: _i18n/zh-Hant/_posts
  label: Traditional Chinese
  create: documents
  match: "*"
  templates:
  - zh-tw-post
- type: directory
  path: _i18n/ko/_posts
  label: Korean
  create: documents
  match: "*"
  exclude: "*.yml"
  templates:
  - ko-post
upload_dir: uploads
public_path: "{{ site.baseurl_root }}/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  - URL=https://plcfmpow8jsc5w.instant.forestry.io/
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
